### ISSUE TITLE
should use password font from options

### ISSUE THREAD

**Issue by TBugReporter** [Rookiestyle/ColoredPassword#3]
I know I'm a [RPITA](https://www.urbandictionary.com/define.php?term=rpita), but I think I liked the non-proportional font better on the password preview tab; the page looks more cluttered this way.

**Comment by Rookiestyle** [comment]
Thanks for making me aware, it's fixed now

**Comment by TBugReporter** [comment]
Looks better now, but it reminded me that it still doesn't use the password font on the main screen.  I seem to recall you saying there was a reason for this, but I don't remember what it was; can you refresh my memory?

**Comment by Rookiestyle** [comment]
I'm afraid I didn't fully understand.

You can adjust the font used for group & entry list in `Tools>Options>Interface (tab)>Select List Font (button)`.
This will affect the password column in the entry list as well.
The password font selected in `Tools>Options>Interface (tab)>Select Password Font (button)` does not affect the entry list's password column. It will only affect the password field in the entry details & the password generator.

Are you referring to the entry list's password column?
I did not manage to have KeePass use a different font than for e. g. "Title" or "User Name" column in a clean KeePass setup without any plugins installed.
A screenshot and a list of potentially other plugins installed might help
